name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  playwright-job:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Run Playwright Tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          API_URL: ${{ secrets.API_URL }}
        run: |
          npm run install-playwright
          npm run install-playwright-deps
          npm run playwright

      - name: Upload Playwright Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 30
